#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrandr --output eDP-1-1 --primary --mode 1920x1080
xrandr --output HDMI-0 --mode 1920x1080 --right-of eDP-1-1 -r 60

feh --bg-fill $HOME/Imagens/wallpaper.png
~/.config/polybar/forest/launch.sh

xsetroot -cursor_name left_ptr &
setxkbmap -model abnt2 -layout br -variant abnt2
picom --experimental-backends &

bspc monitor -d I II III

xrandr --output eDP-1 --brightness .6
